### ISSUE TITLE
Crawler configuration: add 'Config Parameters' reference in documentation

### ISSUE THREAD

**Issue by fbaligand** [codelibs/fess#1862]
There are lots of 'Config Parameters' available to configure a crawler.
But unfortunately, there are currently undocumented.

This would be great to list all possible crawler 'Config Parameters' in official documentation.
Or maybe reference a file on github listing all possible 'Config Parameters'.

**Comment by fbaligand** [comment]
Hi @marevol,

In my mind, this is not a question, but more a documentation enhancement request.

**Comment by fbaligand** [comment]
That said, if you have some location (github file, blog, any link) where all Config Parameters (or at least the major part) are referenced, I would be happy to know it !

**Comment by zackhorvath** [comment]
I'd be really happy to know too!

**Comment by Anders-Bergqvist** [comment]
Me too!

**Comment by marevol** [comment]
#1686

**Comment by fbaligand** [comment]
Hi @marevol,

If I understand well, this issue is closed because it is a duplicate of #1686 ?

**Comment by marevol** [comment]
This issue is a documentation work for us, so I closed it as duplicate.
Fess is an open source product.
Any contributions including documentations are welcome!

**Comment by fbaligand** [comment]
As an open source contributor, I fully understand your purpose!
But it’s complicated to document hidden features that you don’t even know. 
If I open this issue, it is first because I guess there are several useful config parameters, but I don’t know about them.
And honestly, this is quite frustrating.

**Comment by jamiejackson** [comment]
@marevol this is like asking us to read your mind then document what's in there.

It can be hard to reverse-engineer intent from source code. I understand not having time to make documentation pretty or get the wording perfect, but at least give us some scraps to work with that we can then turn into PRs. Even an ugly list of params, written here, would be fine.

Otherwise:

* 99% of potential implementers would not know about configuration options
* The remaining 1% who discover that there are hidden options would then play a guessing game as to what the options do and how to use them

**Comment by stratocentric** [comment]
Has anyone found or started a resource for this?  Suggested topics:

FESS
- kubernetes installation for Digital Ocean
- configuring search
- connecting to various api services like rapidapi
- distributed data resources for JSON

I will host a wiki or similar for this if anyone is interested... also add the topics you want to cover.
