### ISSUE TITLE
Inject data into Fess (Elasticsearch) data store?

### ISSUE THREAD

**Issue by Outstep** [codelibs/fess#2006]
Hello,

I have a data feed that already has the URL, Title, Description, date, etc.. fields returned for a query and am wondering if there is an easy to inject this data into the Elesticsearch data store without having to use the Fess Crawler to crawl or scan the URL?

I was thinking that it might be possible to just inject (import) this data into the Elastisearch indexes but was not sure if it would work. Really more like a real-time "import" feature that I can load pre-existing data into FESS.

Any thoughts or ideas would be greatly appreciated.

**Comment by marevol** [comment]
See [CSV Datastore](https://fess.codelibs.org/12.4/admin/dataconfig-guide.html#csvdatastore).
You can start the crawler by Admin API.

**Comment by lonnieOST** [comment]
Yes, I read up on starting crawlers but was looking for a more direct way to "import" without crawling.

What I have is another system that  can feed can also be queried to get results of a search and I want to feed those results directly in to the data store as the arrive so that Fess can query from them as well.

Think of this in terms of a metacrawler data feed into elasticsearch.

Perhaps, I will have to try to write some type of plugin for Elasticsearch that can do something like this, but I thank you for getting back to me.

**Comment by marevol** [comment]
You can also use [Admin API](https://fess.codelibs.org/lastadoc-fess.html#.api.admin.searchlist.doc::put_d_doc), but it's not a bulk API.

**Comment by lonnieOST** [comment]
Thanks again and I will dig into the Admin API to see what I might be able to do.

Sincerely appreciate your help. :)
