### ISSUE TITLE
By json api, search with label doesn't work?

### ISSUE THREAD

**Issue by lamrongol** [codelibs/fess#462]
This page says json api has labelTypeValue parameter. 
http://fess.osdn.jp/ja/4.0/user/json-response.html

However, I found it ignores label and SearchApiRequestParams class doesn't read label parameter.
https://github.com/codelibs/fess/blob/34242845887df394aadb64662b6dfd50c1ed52da/src/main/java/org/codelibs/fess/api/json/JsonApiManager.java

Currently json api can't use labelTypeValue, is it right?

**Comment by kw-udon** [comment]
In Fess 10.0, the parameter `labelTypeValue` is no longer used and `fields.label` is used instead of it.
http://fess.codelibs.org/ja/10.0/user/json-response.html

However, it is true that the parameter `fields.label` is ignored.
So, I sent a patch for this problem. https://github.com/codelibs/fess/pull/464
